
import React from 'react';
import { Recipe } from '../types';

interface CookbookProps {
  recipes: Recipe[];
  onSelect: (recipe: Recipe) => void;
  onRemove: (recipeId: string, e: React.MouseEvent) => void;
}

const Cookbook: React.FC<CookbookProps> = ({ recipes, onSelect, onRemove }) => {
  return (
    <div className="space-y-8 animate-in fade-in duration-500">
      <div className="flex items-center justify-between mb-8">
        <div>
          <h2 className="text-3xl font-bold text-slate-800 flex items-center gap-3">
            <span>📖</span> My Cookbook
          </h2>
          <p className="text-slate-500 mt-1">Your collection of {recipes.length} saved culinary masterpieces.</p>
        </div>
      </div>

      {recipes.length > 0 ? (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {recipes.map((recipe) => (
            <div
              key={recipe.id}
              onClick={() => onSelect(recipe)}
              className="bg-white rounded-3xl overflow-hidden shadow-sm border border-slate-200 cursor-pointer group hover:shadow-2xl transition-all hover:-translate-y-2 relative"
            >
              <div className="aspect-[4/3] relative overflow-hidden bg-slate-100">
                <img
                  src={recipe.imageUrl || `https://picsum.photos/seed/${recipe.id}/600/400`}
                  alt={recipe.title}
                  className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-700"
                />
                <div className="absolute top-4 left-4 flex flex-wrap gap-2">
                  <span className={`px-3 py-1 rounded-lg text-[10px] font-black uppercase tracking-widest shadow-sm ${
                    recipe.difficulty === 'Easy' ? 'bg-emerald-500 text-white' :
                    recipe.difficulty === 'Medium' ? 'bg-orange-500 text-white' : 'bg-rose-500 text-white'
                  }`}>
                    {recipe.difficulty}
                  </span>
                </div>
                {/* Delete Button */}
                <button
                  onClick={(e) => onRemove(recipe.id, e)}
                  className="absolute top-4 right-4 bg-white/90 p-2 rounded-full text-red-500 shadow-md hover:bg-red-500 hover:text-white transition-all opacity-0 group-hover:opacity-100"
                  title="Remove from Cookbook"
                >
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                    <path fillRule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clipRule="evenodd" />
                  </svg>
                </button>
              </div>
              <div className="p-6">
                <h3 className="text-xl font-bold text-slate-800 group-hover:text-emerald-600 transition-colors line-clamp-1">
                  {recipe.title}
                </h3>
                <p className="text-slate-500 text-sm mb-6 line-clamp-2 leading-relaxed">
                  {recipe.description}
                </p>
                <div className="flex items-center justify-between text-slate-600 text-xs font-bold border-t border-slate-50 pt-5">
                  <div className="flex items-center gap-2">
                    <span className="text-lg">⏱️</span> {recipe.prepTime}
                  </div>
                  <div className="flex items-center gap-2">
                    <span className="text-lg">🔥</span> {recipe.calories} kcal
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      ) : (
        <div className="py-24 text-center bg-white rounded-3xl border border-dashed border-slate-200">
          <div className="text-5xl mb-4">🍽️</div>
          <p className="text-slate-800 font-bold text-lg">Your cookbook is empty</p>
          <p className="text-slate-400 mt-1">Star recipes generated by the AI to save them here.</p>
        </div>
      )}
    </div>
  );
};

export default Cookbook;
